### ISSUE TITLE
Is it possible to release the checkpoint?

### ISSUE THREAD

**Issue by HaozheZhao** [duchenzhuang/FSQ-pytorch#1]
Excellent work, thank you very much for implementing the code. I'm convinced it will be vastly beneficial to the community. 

Could I inquire if you've thought about releasing the checkpoint of your trained FSQ model?

**Comment by duchenzhuang** [comment]
I have uploaded the checkpoints. Please check the Quantitative Results section.

**Comment by HaozheZhao** [comment]
Excellent work!! Thanks Again.
